### ISSUE TITLE
SHA256 mismatch error during installation with Homebrew

### ISSUE THREAD

**Issue by welf** [d1y/scls#9]
There is an error when I try to install `scls` with Homebrew:
```
Error: scls: SHA256 mismatch
Expected: ec62fe91f8baac030802b657ebe01173366c6bdf8a03f72c4cc86b7e65f54870
  Actual: da104265fc1dc98e019a3f7a1895785c9d21be6b9f94a6348e122fba7de3baf7
```

**Comment by d1y** [comment]
I'm not sure what the reason is
But you can take a look at this https://github.com/orgs/Homebrew/discussions/1312

**Comment by szafranek** [comment]
FYI, I have exactly the same problem, even actual checksum was the same. I'm not on VPN.

**Comment by xtrasmal** [comment]
can always build `cargo install --git https://github.com/d1y/scls`
